account_id = ""
name = "my-site"
type = "javascript"
workers_dev = true

[site]
bucket = "public"
entry-point = "dist"

[build]
command = "npm run build && cp package.json dist"
upload_dir = "dist"
upload_format = "modules"
upload_exclude = ["*.map"]
